name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v2 

    - name: Install Pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/3.6.3/pandoc-3.6.3-1-amd64.deb
        sudo dpkg -i pandoc-3.6.3-1-amd64.deb
        pandoc --version

    - name: Run script from the scripts folder
      run: |
        chmod +x ./scripts/transform_files.sh 
        ./scripts/transform_files.sh 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

